### PR TITLE
convience method

### PR DESCRIPTION
**Pull request by jswhisperer**
Not perfect but this reloads when there are changes (still a bit slow) -k kill the process before making a new one, "." the directory to watch, -e exlude "dist/" then the command to run.. npm dev

### CODE REVIEW

**Comment by shubhamzanwar** [comment]
Ah, this is a good thing to implement!
However, there's a way of detecting these changes with webpack and rebuilding automatically. I think it's been implemented in react-nodegui-starter. Will check that and add it here.
Until then, I'm opening an issue #2 for this :)

**Comment by shubhamzanwar** [comment]
Sorry for accidentally closing that!

**Comment by jswhisperer** [comment]
No problem, for sure I knew there was a better way!

**Comment by shubhamzanwar** [comment]
Closing this for now.
I've created a pull request in the vue-loader repo to enable hot-reloading when the webpack target is `node`.
https://github.com/vuejs/vue-loader/pull/1731

Once that's merged, we can implement HMR in vue-nodegui 🙂

**Pull request closed without merging**
